name: Keep-alive

on:
  schedule:
    # Runs every sunday at 3 a.m.
    - cron: '0 3 * * SUN'

jobs:
  call-test-workflow:
    permissions:
      contents: read
      id-token: write
    uses: openbraininstitute/BluePyOpt/.github/workflows/test.yml@master
  
  keep-workflow-alive:
    name: Keep workflow alive
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          ref: master

      - name: commit IF last commit is older than 50 days
        run: |
          datethen=$(date -d "-50 days" --utc +%s)
          last_push=$(git log -1 --format=%ct)
          if [ "$last_push" -le "$datethen" ]; then
            git config user.name "Github Actions Keepalive Bot"
            git config user.email "<>"
            git commit -m "Empty commit to keep the github workflows alive" --allow-empty
            git push origin master
          else
            echo "Last commit is recent enough, skipping keepalive commit."
          fi